apiVersion: 1
datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: influx
    user: admin
    password: admin
    isDefault: true
    jsonData:
      httpMode: GET
    uid: influxdb_uid  # Specify the UID for the datasource
