{
 "title": "MundosE",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Docker Containers | Telegraf",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"usage_guest\") FROM \"cpu\" WHERE (\"host\" = 'docker-telegraf' AND \"os\" = 'Linux' AND \"environment\" = 'Dev') AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "usage_guest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "docker-telegraf-second" },
      { "condition": "AND", "key": "os", "operator": "=", "value": "Linux" },
      { "condition": "AND", "key": "environment", "operator": "=", "value": "Dev" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"usage_guest\") FROM \"cpu\" WHERE (\"host\" = 'docker-telegraf' AND \"os\" = 'Linux' AND \"environment\" = 'Dev') AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "usage_guest" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "docker-telegraf-second" },
      { "condition": "AND", "key": "os", "operator": "=", "value": "Linux" },
      { "condition": "AND", "key": "environment", "operator": "=", "value": "Dev" }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "query": "SELECT mean(\"usage_guest\") FROM \"cpu\" WHERE (\"host\" = 'docker-telegraf' AND \"os\" = 'Linux' AND \"environment\" = 'Dev') AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "docker-telegraf-second" },
      { "condition": "AND", "key": "os", "operator": "=", "value": "Linux" },
      { "condition": "AND", "key": "environment", "operator": "=", "value": "Dev" }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"usage_guest\") FROM \"cpu\" WHERE (\"host\" = 'docker-telegraf' AND \"os\" = 'Linux' AND \"environment\" = 'Dev') AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "usage_guest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "docker-telegraf" },
      { "condition": "AND", "key": "os", "operator": "=", "value": "Linux" },
      { "condition": "AND", "key": "environment", "operator": "=", "value": "Dev" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"usage_guest\") FROM \"cpu\" WHERE (\"host\" = 'docker-telegraf' AND \"os\" = 'Linux' AND \"environment\" = 'Dev') AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "usage_guest" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "docker-telegraf" },
      { "condition": "AND", "key": "os", "operator": "=", "value": "Linux" },
      { "condition": "AND", "key": "environment", "operator": "=", "value": "Dev" }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "query": "SELECT mean(\"usage_guest\") FROM \"cpu\" WHERE (\"host\" = 'docker-telegraf' AND \"os\" = 'Linux' AND \"environment\" = 'Dev') AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "docker-telegraf" },
      { "condition": "AND", "key": "os", "operator": "=", "value": "Linux" },
      { "condition": "AND", "key": "environment", "operator": "=", "value": "Dev" }
     ]
    }
   ]
  },
  {
   "title": "Debian",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_guest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "WSL-debian" },
      { "condition": "AND", "key": "customer", "operator": "=", "value": "DevOpsea" },
      { "condition": "AND", "key": "os", "operator": "=", "value": "Linux" },
      { "condition": "AND", "key": "environment", "operator": "=", "value": "Dev" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "mem",
     "query": "SELECT mean(\"Available_Bytes\") FROM \"win_mem\" WHERE ($timeFilter GROUP BY time($__interval), \"host\" fill(linear)",
     "select": [
      [
       { "params": [ "available" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "WSL-debian" },
      { "condition": "AND", "key": "customer", "operator": "=", "value": "DevOpsea" },
      { "condition": "AND", "key": "os", "operator": "=", "value": "Linux" },
      { "condition": "AND", "key": "environment", "operator": "=", "value": "Dev" }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "host::tag" ], "type": "tag" }
     ],
     "measurement": "disk",
     "query": "SELECT \"free\" FROM \"disk\" WHERE (\"host\" = 'WSL-debian' AND \"customer\" = 'DevOpsea' AND \"os\" = 'Linux' AND \"environment\" = 'Dev' AND \"path\" = '/mnt/c') AND $timeFilter GROUP BY \"host\"::tag",
     "select": [
      [
       { "params": [ "free" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "WSL-debian" },
      { "condition": "AND", "key": "customer", "operator": "=", "value": "DevOpsea" },
      { "condition": "AND", "key": "os", "operator": "=", "value": "Linux" },
      { "condition": "AND", "key": "environment", "operator": "=", "value": "Dev" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/mnt/c" }
     ]
    },
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "host::tag" ], "type": "tag" }
     ],
     "measurement": "disk",
     "query": "SELECT \"free\" FROM \"disk\" WHERE (\"host\" = 'WSL-debian' AND \"customer\" = 'DevOpsea' AND \"os\" = 'Linux' AND \"environment\" = 'Dev' AND \"path\" = '/mnt/c') AND $timeFilter GROUP BY \"host\"::tag",
     "select": [
      [
       { "params": [ "free" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "WSL-debian" },
      { "condition": "AND", "key": "customer", "operator": "=", "value": "DevOpsea" },
      { "condition": "AND", "key": "os", "operator": "=", "value": "Linux" },
      { "condition": "AND", "key": "environment", "operator": "=", "value": "Dev" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/mnt/e" }
     ]
    }
   ]
  },
  {
   "title": "Windows 11",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "win_cpu",
     "select": [
      [
       { "params": [ "Percent_Processor_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mundose-dev" },
      { "condition": "AND", "key": "customer", "operator": "=", "value": "DevOpsea" },
      { "condition": "AND", "key": "os", "operator": "=", "value": "Windows" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "win_mem",
     "query": "SELECT mean(\"Available_Bytes\") FROM \"win_mem\" WHERE ($timeFilter GROUP BY time($__interval), \"host\" fill(linear)",
     "select": [
      [
       { "params": [ "Available_Bytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mundose-dev" },
      { "condition": "AND", "key": "customer", "operator": "=", "value": "DevOpsea" },
      { "condition": "AND", "key": "os", "operator": "=", "value": "Windows" }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "win_disk",
     "select": [
      [
       { "params": [ "Free_Megabytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mundose-dev" },
      { "condition": "AND", "key": "customer", "operator": "=", "value": "DevOpsea" },
      { "condition": "AND", "key": "os", "operator": "=", "value": "Windows" }
     ]
    }
   ]
  }
 ]
}